my changes

diff --git a/minecraft-server/start-deployBukkitSpigot b/minecraft-server/start-deployBukkitSpigot
--- a/minecraft-server/start-deployBukkitSpigot
+++ b/minecraft-server/start-deployBukkitSpigot
@@ -4,7 +4,7 @@ function buildSpigotFromSource {
   echo "Building Spigot $VANILLA_VERSION from source, might take a while, get some coffee"
   mkdir /data/temp
   cd /data/temp
-  curl -sSL -o /data/temp/BuildTools.jar https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && \
+  wget -q -P /data/temp https://hub.spigotmc.org/jenkins/job/BuildTools/lastSuccessfulBuild/artifact/target/BuildTools.jar && \
     java -jar /data/temp/BuildTools.jar --rev $VANILLA_VERSION 2>&1 |tee /data/spigot_build.log| while read l; do echo -n .; done; echo "done"
   mv spigot-*.jar /data/spigot_server.jar
   mv craftbukkit-*.jar /data/craftbukkit_server.jar
@@ -17,40 +17,33 @@ function downloadSpigot {
   local match
   case "$TYPE" in
     *BUKKIT|*bukkit)
-      match="CraftBukkit"
+      match="Craftbukkit"
       downloadUrl=${BUKKIT_DOWNLOAD_URL}
-      getbukkitFlavor=craftbukkit
       ;;
     *)
       match="Spigot"
       downloadUrl=${SPIGOT_DOWNLOAD_URL}
-      getbukkitFlavor=spigot
       ;;
   esac
 
-  local downloadVersion
-  if [[ ${VERSION} == LATEST ]]; then
-    downloadVersion=${VANILLA_VERSION}
-  else
-    downloadVersion=${VERSION}
-  fi
-
   if [[ -z $downloadUrl ]]; then
-    downloadUrl="https://cdn.getbukkit.org/${getbukkitFlavor}/${getbukkitFlavor}-${downloadVersion}.jar"
+    downloadUrl=$(restify --class=jar-div https://getbukkit.org/download/ | \
+      jq --arg version "$match $VANILLA_VERSION" -r -f /usr/share/mcadmin.jq)
+    if [[ -z $downloadUrl ]]; then
+      echo "ERROR: Version $VANILLA_VERSION is not supported for $TYPE"
+      echo "       Refer to https://mcadmin.net/ for supported versions"
+      exit 2
+    fi
   fi
 
-  echo "Downloading $match from $downloadUrl ..."
-  curl -fsSL -o $SERVER "$downloadUrl"
-  if [[ $? != 0 || $(grep -c "DOCTYPE html" $SERVER) != 0 ]]; then
-    cat <<EOF
-
-ERROR: failed to download from $downloadUrl
-       Visit https://getbukkit.org/download/${getbukkitFlavor} to lookup the
-       exact version, such as 1.4.6-R0.4-SNAPSHOT or 1.8-R0.1-SNAPSHOT-LATEST
-
-EOF
+  echo "Downloading $match"
+  curl -kfsSL -o $SERVER "$downloadUrl"
+  status=$?
+  if [ ! -f $SERVER ]; then
+    echo "ERROR: failed to download from $downloadUrl (status=$status)"
     exit 3
   fi
+
 }
 
 
diff --git a/minecraft-server/start-deployFTB b/minecraft-server/start-deployFTB
--- a/minecraft-server/start-deployFTB
+++ b/minecraft-server/start-deployFTB
@@ -1,108 +1,68 @@
 #!/bin/bash
 
-. /start-utils
-
-export FTB_BASE_DIR=/data/FeedTheBeast
-legacyJavaFixerUrl=http://ftb.cursecdn.com/FTB2/maven/net/minecraftforge/lex/legacyjavafixer/1.0/legacyjavafixer-1.0.jar
 export TYPE=FEED-THE-BEAST
 
-FTB_SERVER_MOD=${FTB_SERVER_MOD:-$CF_SERVER_MOD}
+function isURL {
+  local value=$1
 
-echo "Looking for Feed-The-Beast / CurseForge server modpack."
+  if [[ ${value:0:8} == "https://" || ${value:0:7} = "http://" ]]; then
+    return 0
+  else
+    return 1
+  fi
+}
+
+echo "Looking for Feed-The-Beast server modpack."
 if [[ -z $FTB_SERVER_MOD ]]; then
     echo "Environment variable FTB_SERVER_MOD not set."
     echo "Set FTB_SERVER_MOD to the file name of the FTB server modpack."
     echo "(And place the modpack in the /data directory.)"
     exit 2
 fi
-
-entryScriptExpr="-name ServerStart.sh -o -name ServerStartLinux.sh -o -name LaunchServer.sh"
-
-if [[ -d ${FTB_BASE_DIR} ]]; then
-  startScriptCount=$(find ${FTB_BASE_DIR} $entryScriptExpr |wc -l)
-  if [[ $startScriptCount > 1 ]]; then
-    echo "Conflicting FTB/CurseForge packages have been installed. Please cleanup ${FTB_BASE_DIR}"
+srv_modpack=${FTB_SERVER_MOD}
+if isURL ${srv_modpack}; then
+    case $srv_modpack in
+      https://www.feed-the-beast.com/*/download)
+        break;;
+      https://www.feed-the-beast.com/*)
+        srv_modpack=${srv_modpack}/download;;
+    esac
+    file=$(basename $(dirname $srv_modpack))
+    downloaded=/data/${file}.zip
+    if [ ! -e $downloaded ]; then
+      echo "Downloading FTB modpack...
+$srv_modpack -> $downloaded"
+      curl -sSL -o $downloaded $srv_modpack
+    fi
+    srv_modpack=$downloaded
+fi
+if [[ ${srv_modpack:0:5} == "data/" ]]; then
+    # Prepend with "/"
+    srv_modpack=/${srv_modpack}
+fi
+if [[ ! ${srv_modpack:0:1} == "/" ]]; then
+    # If not an absolute path, assume file is in "/data"
+    srv_modpack=/data/${srv_modpack}
+fi
+if [[ ! -f ${srv_modpack} ]]; then
+    echo "FTB server modpack ${srv_modpack} not found."
     exit 2
-  fi
-else
-  startScriptCount=0
+fi
+if [[ ! ${srv_modpack: -4} == ".zip" ]]; then
+    echo "FTB server modpack ${srv_modpack} is not a zip archive."
+    echo "Please set FTB_SERVER_MOD to a file with a .zip extension."
+    exit 2
 fi
 
-# only download and install if a mod pack isn't already installed
-# also check for the start script rather than just the folder
-# this allows saving just the world separate from the rest of the data directory
-if [[ $startScriptCount = 0 ]]; then
-  srv_modpack=${FTB_SERVER_MOD}
-  if isURL ${srv_modpack}; then
-      case $srv_modpack in
-        https://www.feed-the-beast.com/*/download|https://minecraft.curseforge.com/*/download)
-          ;;
-        https://www.feed-the-beast.com/*|https://minecraft.curseforge.com/*)
-          srv_modpack=${srv_modpack}/download;;
-      esac
-      file=$(basename $(dirname $srv_modpack))
-      downloaded=/data/${file}.zip
-      if [ ! -e $downloaded ]; then
-        echo "Downloading FTB modpack...
-  $srv_modpack -> $downloaded"
-        curl -sSL -o $downloaded $srv_modpack
-      fi
-      srv_modpack=$downloaded
-  fi
-  if [[ ${srv_modpack:0:5} == "data/" ]]; then
-      # Prepend with "/"
-      srv_modpack=/${srv_modpack}
-  fi
-  if [[ ! ${srv_modpack:0:1} == "/" ]]; then
-      # If not an absolute path, assume file is in "/data"
-      srv_modpack=/data/${srv_modpack}
-  fi
-  if [[ ! -f ${srv_modpack} ]]; then
-      echo "FTB server modpack ${srv_modpack} not found."
-      exit 2
-  fi
-  if [[ ! ${srv_modpack: -4} == ".zip" ]]; then
-      echo "FTB server modpack ${srv_modpack} is not a zip archive."
-      echo "Please set FTB_SERVER_MOD to a file with a .zip extension."
-      exit 2
-  fi
-
+if [ ! -d ${FTB_DIR} ]; then
   echo "Unpacking FTB server modpack ${srv_modpack} ..."
-  mkdir -p ${FTB_BASE_DIR}
-  unzip -o ${srv_modpack} -d ${FTB_BASE_DIR} | awk '{printf "."} END {print ""}'
+  mkdir -p ${FTB_DIR}
+  unzip -o ${srv_modpack} -d ${FTB_DIR}
+  cp -f /data/eula.txt ${FTB_DIR}/eula.txt
 fi
-
-if [[ $(find ${FTB_BASE_DIR} $entryScriptExpr |wc -l) = 0 ]]; then
-    echo "Please make sure you are using the server version of the FTB modpack!"
-    exit 2
-fi
-
-export FTB_SERVER_START=$(find ${FTB_BASE_DIR} $entryScriptExpr)
-if [[ $(echo ${FTB_SERVER_START} | wc -w) != 1 ]]; then
-    echo "Please make sure you are using the server version of the FTB modpack!"
-    exit 2
-fi
-
-export FTB_DIR=$(dirname ${FTB_SERVER_START})
+export FTB_SERVER_START=${FTB_DIR}/ServerStart.sh
 chmod a+x ${FTB_SERVER_START}
-sed -i 's/-jar/-Dfml.queryResult=confirm -jar/' ${FTB_SERVER_START}
-sed -i 's/.*read.*Restart now/#\0/' ${FTB_SERVER_START}
-legacyJavaFixerPath=${FTB_DIR}/mods/legacyjavafixer.jar
-
-if isTrue ${FTB_LEGACYJAVAFIXER} && [ ! -e ${legacyJavaFixerPath} ]; then
-  echo "Installing legacy java fixer to ${legacyJavaFixerPath}"
-  curl -sSL -o ${legacyJavaFixerPath} ${legacyJavaFixerUrl}
-fi
-
-if [ -e ${FTB_DIR}/FTBInstall.sh ]; then
-  pushd ${FTB_DIR}
-  sh FTBInstall.sh
-  popd
-elif [ -e ${FTB_DIR}/Install.sh ]; then
-  pushd ${FTB_DIR}
-  sh Install.sh
-  popd
-fi
+sed -i "s/-jar/-Dfml.queryResult=confirm -jar/" ${FTB_SERVER_START}
 
 # Continue to Final Setup
 exec /start-finalSetup01World $@
diff --git a/minecraft-server/start-finalSetup04ServerProperties b/minecraft-server/start-finalSetup04ServerProperties
--- a/minecraft-server/start-finalSetup04ServerProperties
+++ b/minecraft-server/start-finalSetup04ServerProperties
@@ -5,53 +5,22 @@ function setServerProp {
   local prop=$1
   local var=$2
   if [ -n "$var" ]; then
-    # normalize booleans
-    case ${var^^} in
-      TRUE|FALSE)
-        var=${var,,} ;;
-    esac
-    echo "Setting ${prop} to '${var}' in ${SERVER_PROPERTIES}"
-    sed -i "/^${prop}\s*=/ c ${prop}=${var}" $SERVER_PROPERTIES
-  else
-    echo "Skip setting ${prop}"
+    echo "Setting $prop to $var"
+    sed -i "/$prop\s*=/ c $prop=$var" /data/server.properties
   fi
 }
 
 # Deploy server.properties file
-if [ ! -e $SERVER_PROPERTIES ]; then
-  echo "Creating server.properties in ${SERVER_PROPERTIES}"
-  cp /tmp/server.properties $SERVER_PROPERTIES
-
-  if [[ ${TYPE} == "FEED-THE-BEAST" ]]; then
-    export SERVER_PROPERTIES=${FTB_DIR}/server.properties
-    echo "detected FTB, changing properties path to ${SERVER_PROPERTIES}"
-    cp /tmp/server.properties $SERVER_PROPERTIES
-  fi
+if [ ! -e server.properties ]; then
+  echo "Creating server.properties"
+  cp /tmp/server.properties .
 
   if [ -n "$WHITELIST" ]; then
     echo "Creating whitelist"
-    setServerProp "whitelist" "true"
-    setServerProp "white-list" "true"
+    sed -i "/whitelist\s*=/ c whitelist=true" /data/server.properties
+    sed -i "/white-list\s*=/ c white-list=true" /data/server.properties
   fi
 
-  # If not provided, generate a reasonable default message-of-the-day,
-  # which shows up in the server listing in the client
-  if [ -z "$MOTD" ]; then
-    # snapshot is the odd case where we have to look at version to identify that label
-    if [[ ${ORIGINAL_TYPE} == "VANILLA" && ${VERSION} == "SNAPSHOT" ]]; then
-      label=SNAPSHOT
-    else
-      label=${ORIGINAL_TYPE}
-    fi
-
-    # Convert label to title-case
-    label=${label,,}
-    label=${label^}
-    MOTD="A ${label} Minecraft Server powered by Docker"
-  fi
-
-  setServerProp "server-name" "$SERVER_NAME"
-  setServerProp "server-port" "$SERVER_PORT"
   setServerProp "motd" "$MOTD"
   setServerProp "allow-nether" "$ALLOW_NETHER"
   setServerProp "announce-player-achievements" "$ANNOUNCE_PLAYER_ACHIEVEMENTS"
@@ -62,10 +31,9 @@ if [ ! -e $SERVER_PROPERTIES ]; then
   setServerProp "generate-structures" "$GENERATE_STRUCTURES"
   setServerProp "view-distance" "$VIEW_DISTANCE"
   setServerProp "hardcore" "$HARDCORE"
-  setServerProp "snooper-enabled" "$SNOOPER_ENABLED"
   setServerProp "max-build-height" "$MAX_BUILD_HEIGHT"
   setServerProp "force-gamemode" "$FORCE_GAMEMODE"
-  setServerProp "max-tick-time" "$MAX_TICK_TIME"
+  setServerProp "hardmax-tick-timecore" "$MAX_TICK_TIME"
   setServerProp "enable-query" "$ENABLE_QUERY"
   setServerProp "query.port" "$QUERY_PORT"
   setServerProp "enable-rcon" "$ENABLE_RCON"
@@ -78,8 +46,22 @@ if [ ! -e $SERVER_PROPERTIES ]; then
   setServerProp "pvp" "$PVP"
   setServerProp "generator-settings" "$GENERATOR_SETTINGS"
   setServerProp "online-mode" "$ONLINE_MODE"
-  setServerProp "allow-flight" "$ALLOW_FLIGHT"
-  setServerProp "level-type" "${LEVEL_TYPE^^}"
+
+  if [ -n "$LEVEL_TYPE" ]; then
+    # normalize to uppercase
+    LEVEL_TYPE=$( echo ${LEVEL_TYPE} | tr '[:lower:]' '[:upper:]' )
+    echo "Setting level type to $LEVEL_TYPE"
+    # check for valid values and only then set
+    case $LEVEL_TYPE in
+      DEFAULT|FLAT|LARGEBIOMES|AMPLIFIED|CUSTOMIZED|BIOMESOP|RTG)
+        sed -i "/level-type\s*=/ c level-type=$LEVEL_TYPE" /data/server.properties
+        ;;
+      *)
+        echo "Invalid LEVEL_TYPE: $LEVEL_TYPE"
+        exit 1
+        ;;
+    esac
+  fi
 
   if [ -n "$DIFFICULTY" ]; then
     case $DIFFICULTY in
@@ -100,7 +82,8 @@ if [ ! -e $SERVER_PROPERTIES ]; then
         exit 1
         ;;
     esac
-    setServerProp "difficulty" "$DIFFICULTY"
+    echo "Setting difficulty to $DIFFICULTY"
+    sed -i "/difficulty\s*=/ c difficulty=$DIFFICULTY" /data/server.properties
   fi
 
   if [ -n "$MODE" ]; then
@@ -126,10 +109,9 @@ if [ ! -e $SERVER_PROPERTIES ]; then
         exit 1
         ;;
     esac
-    setServerProp "gamemode" "$MODE"
+
+    sed -i "/^gamemode\s*=/ c gamemode=$MODE" $SERVER_PROPERTIES
   fi
-else
-  echo "server.properties already created, skipping"
 fi
 
 exec /start-minecraftFinalSetup $@
